version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    hostname: mongo
    volumes:
      - ./db:/data/db

  app:
    build: ./app
    restart: always
    hostname: app
    volumes:
      - ./app:/data/app
      - ./exploits:/data/exploits
      - ./config.json:/data/config.json
      - logs:/data/logs

  web:
    build: ./web
    ports:
      - 5000:5000
    restart: always
    hostname: web
    volumes:
      - ./web:/data/web
      - logs:/data/logs

volumes:
  logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './logs'
