version: '3.8'

services:
  mongo:
    image: mongo
#    ports:
#      - 27017:27017
    restart: always
    hostname: mongo
    environment:
      TZ: Europe/Rome
    volumes:
      - ./db:/data/db

  app:
    build: ./app
    restart: always
    hostname: app
    environment:
      TZ: Europe/Rome
    volumes:
      - ./app:/data/app
      - logs:/data/logs
      - exploits:/data/exploits
      - configs:/data/configs

  web:
    build: ./web
    ports:
      - 5000:7070
    restart: always
    hostname: web
    environment:
      TZ: Europe/Rome
    volumes:
      - ./web:/data/web
      - logs:/data/logs
      - exploits:/data/exploits
      - configs:/data/configs

volumes:
  logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './logs'

  exploits:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './exploits'

  configs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './configs'
