[project]
name = "milkman"
version = "0.0.1"
dependencies = [
    "requests",
    "pymongo",
    "watchdog",
    "inotify",
    "loguru"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["milkman"]
